/**
 * dsh-intercom e2e driver (`pnpm test:e2e`). Not part of `pnpm test`: it boots
 * a REAL dsh process against the mock LLM server, so it needs a built lib/ and
 * takes seconds rather than milliseconds.
 *
 * Steps:
 *   1. Start `@deepseek-ai/dsh-llm-mock-server` scripted to answer the first
 *      model request with `tool_call_success` (intercom send → worker) and
 *      every later request with a plain success.
 *   2. Generate a patch overlay under tests/e2e/.tmp that disables the
 *      headless one-shot runner and the LLM session titler (it would consume
 *      mock sequence entries), then inserts dsh-intercom (compiled lib/) and
 *      the scenario plugin by file URL.
 *   3. Spawn `node <dsh bin> --profile headless --patch <overlay>` with a
 *      scratch DSH_HOME and DEEPSEEK_BASE_URL pointing at the mock.
 *   4. The scenario plugin (runner-plugin.mjs) prints `[e2e] PASS` and exits 0
 *      on success; this driver mirrors the child output and exit code.
 *
 * Windows-safe: the dsh bin is resolved from `npm root -g` (or $DSH_BIN) and
 * spawned through process.execPath.
 */
import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import type { ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import { startMockLlmServer } from "@deepseek-ai/dsh-llm-mock-server";

const E2E_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(E2E_DIR, "..", "..");
const TMP_DIR = join(E2E_DIR, ".tmp");
const DSH_HOME = join(TMP_DIR, "dsh-home");
const CHILD_TIMEOUT_MS = 170_000;

function resolveDshBin(): string {
  if (process.env.DSH_BIN) return process.env.DSH_BIN;
  // npm is a .cmd shim on Windows; route through the shell so it resolves.
  const globalRoot = execFileSync("npm root -g", {
    encoding: "utf8",
    shell: true,
  }).trim();
  return join(globalRoot, "@deepseek-ai", "dsh", "lib", "bin.js");
}

async function main(): Promise<void> {
  const pluginEntry = join(REPO_ROOT, "lib", "src", "index.js");
  assert.ok(
    existsSync(pluginEntry),
    "lib/src/index.js missing — run `pnpm build` first",
  );

  const mock = await startMockLlmServer({
    port: 0,
    sequence: ["tool_call_success", "success"],
    repeatLast: true,
    toolName: "intercom",
    toolArguments: JSON.stringify({
      action: "send",
      to: "worker",
      message: "hello from planner",
    }),
    successText: "mock ack",
  });

  let child: ChildProcess | undefined;
  try {
    await rm(TMP_DIR, { recursive: true, force: true });
    await mkdir(DSH_HOME, { recursive: true });

    const patchPath = join(TMP_DIR, "e2e.patch.yml");
    const patch = `# Generated by tests/e2e/run.ts — scratch headless profile overlay.
# The LLM titler would consume mock sequence entries; the one-shot runner
# requires a task positional. The e2e runner plugin drives the scenario itself.
- id: session-title-llm
  disabled: true
- id: headless-runner
  disabled: true
- id: headless-startup
  disabled: true

- insert:
    - id: dsh-intercom
      name: '${pathToFileURL(pluginEntry).href}'
    - id: dsh-intercom-e2e
      name: '${pathToFileURL(join(E2E_DIR, "runner-plugin.mjs")).href}'
`;
    await writeFile(patchPath, patch);

    const bin = resolveDshBin();
    const proc = spawn(
      process.execPath,
      [bin, "--profile", "headless", "--patch", patchPath],
      {
        env: {
          ...process.env,
          DSH_HOME,
          DEEPSEEK_BASE_URL: mock.baseURL,
          DEEPSEEK_API_KEY: "e2e-mock-key",
          NO_COLOR: "1",
        },
        stdio: ["ignore", "pipe", "pipe"],
      },
    );
    child = proc;

    const output: string[] = [];
    proc.stdout.on("data", (chunk: Buffer) => {
      process.stdout.write(chunk);
      output.push(String(chunk));
    });
    proc.stderr.on("data", (chunk: Buffer) => {
      process.stderr.write(chunk);
      output.push(String(chunk));
    });

    const code = await new Promise<number | null>((resolvePromise) => {
      const killer = setTimeout(() => {
        proc.kill();
        resolvePromise(null);
      }, CHILD_TIMEOUT_MS);
      proc.on("exit", (exitCode) => {
        clearTimeout(killer);
        resolvePromise(exitCode);
      });
    });

    assert.ok(
      code !== null,
      `dsh process timed out after ${CHILD_TIMEOUT_MS}ms`,
    );
    assert.equal(code, 0, "dsh process exited non-zero");
    assert.ok(
      output.join("").includes("[e2e] PASS"),
      "scenario did not report PASS",
    );
    console.log("[e2e] driver: dsh exited 0 with PASS");
  } finally {
    child?.kill();
    await mock.close();
  }
}

main().catch((error: unknown) => {
  console.error(
    `[e2e] driver failed: ${error instanceof Error ? (error.stack ?? error.message) : String(error)}`,
  );
  process.exit(1);
});
